from __future__ import annotations

from typing import Any

from ._common import evidence
from .inventory import SOURCE_INVENTORY

# Every record below is bound to the exact source Git SHA and pyproject.toml
# blob observed for that SHA. These are migration inputs, not aliases.
SOURCE_INTERFACES: tuple[dict[str, Any], ...] = (
    {
        "repository": "agentmesh",
        "source_sha": "320f5116f6582519d1609ce87287fd9ff7267eb3",
        "pyproject_blob_sha": "895dfd0aa69a92e4bb1844e6b2f94872c0f406c9",
        "project_name": "agentmesh",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "agentmesh",
        "source_entrypoint": "agentmesh.cli:main",
        "import_root": "agentmesh",
        "target_module": "routing_evidence",
        "prepared_target_cli": ["agentops route"],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "agent-budgeter",
        "source_sha": "cfa9c0a8830f3e2e3a11602da590e347f8483d2f",
        "pyproject_blob_sha": "c01d0464e2fefd9c490c3499953e4deced9a8797",
        "project_name": "agent-budgeter",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "agent-budgeter",
        "source_entrypoint": "agent_budgeter.cli:main",
        "import_root": "agent_budgeter",
        "target_module": "budgets",
        "prepared_target_cli": [],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "agent-inbox",
        "source_sha": "748f237659f98a2a49478aa58913e71e59a03433",
        "pyproject_blob_sha": "c28cbc197b14a40aa9dc353dbf5f0004608cbcdd",
        "project_name": "agent-inbox",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "agent-inbox",
        "source_entrypoint": "agent_inbox.cli:main",
        "import_root": "agent_inbox",
        "target_module": "operator_inbox",
        "prepared_target_cli": ["agentops inbox"],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "agent-quota-simulator",
        "source_sha": "e99000cecf12432365e8ccfc8fa6e4b1d18ad15f",
        "pyproject_blob_sha": "23824bcc6ac9fc2b4aa0e1099eb515d56c5a1f52",
        "project_name": "agent-quota-simulator",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "agent-quota-simulator",
        "source_entrypoint": "agent_quota_simulator:main",
        "import_root": "agent_quota_simulator",
        "target_module": "quota_simulation",
        "prepared_target_cli": ["agentops quota"],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "agent-retry-kit",
        "source_sha": "38f97aaa6796fda6956202aad9086e3e5e8ada9f",
        "pyproject_blob_sha": "45b943969d45fd6e765dc45e6639ad0fa702ea9e",
        "project_name": "agent-retry-kit",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "agent-retry-kit",
        "source_entrypoint": "agent_retry_kit.cli:main",
        "import_root": "agent_retry_kit",
        "target_module": "retry_policy",
        "prepared_target_cli": [],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "agent-session-recorder",
        "source_sha": "2363c4efe0c61158c523a6dfc3d29cb3d7af1c54",
        "pyproject_blob_sha": "7b1060bfae9f3e28106a68e54f8a66b7f8048773",
        "project_name": "agent-session-recorder",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "agent-session-recorder",
        "source_entrypoint": "agent_session_recorder:main",
        "import_root": "agent_session_recorder",
        "target_module": "session_evidence",
        "prepared_target_cli": ["agentops session-record", "agentops session-verify"],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "circuit-breaker-lab",
        "source_sha": "2924dfb6eed8a208788491fa1d50fa6bd99e4359",
        "pyproject_blob_sha": "a05ace2291ed5fac36ee1e7c3364bca870f7c14b",
        "project_name": "circuit-breaker-lab",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "circuit-breaker-lab",
        "source_entrypoint": "circuit_breaker_lab.cli:main",
        "import_root": "circuit_breaker_lab",
        "target_module": "circuit_breakers",
        "prepared_target_cli": ["agentops circuit"],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "context-window-budgeter",
        "source_sha": "35bb3e05d05ad870715b740143c429f08eda25e7",
        "pyproject_blob_sha": "4cf33f2e61cd0437058f2347cc9bad8c257e5a66",
        "project_name": "context-window-budgeter",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "context-budget",
        "source_entrypoint": "context_window_budgeter:main",
        "import_root": "context_window_budgeter",
        "target_module": "context_budgets",
        "prepared_target_cli": ["agentops context"],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "human-in-the-loop-queue",
        "source_sha": "db281bf7ff971a2fd4ca6af9e495b2c0fd6cd30b",
        "pyproject_blob_sha": "09e879c53006d47ac825a3d43494d0b75c181d1a",
        "project_name": "human-in-the-loop-queue",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "human-in-the-loop-queue",
        "source_entrypoint": "human_in_the_loop_queue.cli:main",
        "import_root": "human_in_the_loop_queue",
        "target_module": "approvals_queue",
        "prepared_target_cli": [],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "idempotency-kit",
        "source_sha": "80e78a4d9b73aeabb200578c2ecb5090f31a410f",
        "pyproject_blob_sha": "39f72892d20868a07db6ff61b00a3ab5237c5c66",
        "project_name": "idempotency-kit",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "idempotency-kit",
        "source_entrypoint": "idempotency_kit.cli:main",
        "import_root": "idempotency_kit",
        "target_module": "idempotency",
        "prepared_target_cli": [],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "taskgraph",
        "source_sha": "937abf0d096cb1f6ff48aa09b8dd8a69d9a36c0d",
        "pyproject_blob_sha": "2ed2b307ea2b6974ab34adfc2dc404346bb3ca21",
        "project_name": "taskgraph-agents",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "taskgraph",
        "source_entrypoint": "taskgraph.cli:main",
        "import_root": "taskgraph",
        "target_module": "task_graph",
        "prepared_target_cli": [],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "timeout-toolkit",
        "source_sha": "a2a053e39a6eaa40cde7d81f87ee4838cf562583",
        "pyproject_blob_sha": "4d109435f19c59af26ac53e260ad017f33e05098",
        "project_name": "timeout-toolkit",
        "version": "0.1.0",
        "requires_python": ">=3.11",
        "source_cli": "timeout-toolkit",
        "source_entrypoint": "timeout_toolkit.cli:main",
        "import_root": "timeout_toolkit",
        "target_module": "timeouts",
        "prepared_target_cli": [],
        "legacy_alias_state": "not_activated",
        "compatibility_fixture_state": "not_run",
    },
    {
        "repository": "automation-control-plane",
        "source_sha": "42920b932e1eeb9acf143907a7283453cf03eb81",
        "pyproject_blob_sha": "7b1764d7407ca6da3238fd59ac306835b87820c6",
        "project_name": "automation-control-plane",
        "version": "1.0.0",
        "requires_python": ">=3.11",
        "source_cli": "automation-control-plane",
        "source_entrypoint": "automation_control_plane.cli:main",
        "import_root": "automation_control_plane",
        "target_module": "core",
        "prepared_target_cli": ["automation-control-plane", "agentops"],
        "legacy_alias_state": "not_applicable",
        "compatibility_fixture_state": "base_regression_covered",
    },
)


def compatibility_inventory() -> dict[str, Any]:
    expected = {item["repository"]: item["main_sha"] for item in SOURCE_INVENTORY}
    observed = {item["repository"]: item["source_sha"] for item in SOURCE_INTERFACES}
    source_sha_match = expected == observed
    payload = {
        "interfaces": list(SOURCE_INTERFACES),
        "source_sha_match": source_sha_match,
    }
    details = {
        **payload,
        "interface_count": len(SOURCE_INTERFACES),
        "legacy_aliases_activated": False,
        "migration_performed": False,
        "compatibility_gate": "not_run",
        "rule": "inventory exact source surfaces before aliases; compatibility fixtures and human approval precede migration",
    }
    return evidence(
        "compatibility_inventory",
        "passed" if source_sha_match and len(SOURCE_INTERFACES) == len(SOURCE_INVENTORY) else "failed",
        payload,
        details,
    )
