import type { DashboardSnapshot } from "@/lib/contracts";

export const demoSnapshot: DashboardSnapshot = {
  provenance: {
    source: "synthetic-demo-api",
    fetchedAt: "2026-08-15T14:32:18.000Z",
    generatedBy: "agent-dashboard-fixture-v1",
    schemaVersion: "1.0",
    synthetic: true,
  },
  budgetUsd: 12,
  agents: [
    {
      id: "atlas",
      name: "Atlas",
      role: "Repository analyst",
      status: "running",
      runId: "run-1048",
      task: "Map package boundaries and ownership",
      startedAt: "2026-08-15T14:18:02.000Z",
      updatedAt: "2026-08-15T14:31:51.000Z",
      durationSeconds: 829,
      costUsd: 1.84,
      tokens: 28420,
      progress: 72,
      retries: 0,
      maxRetries: 2,
      result: null,
      logs: ["Loaded 46 public source files", "Grouped modules into 8 ownership areas", "Validating two ambiguous dependency edges"],
      allowedActions: ["inspect", "export"],
    },
    {
      id: "lumen",
      name: "Lumen",
      role: "Test engineer",
      status: "waiting",
      runId: "run-1049",
      task: "Verify checkout recovery journey",
      startedAt: "2026-08-15T14:21:14.000Z",
      updatedAt: "2026-08-15T14:30:42.000Z",
      durationSeconds: 568,
      costUsd: 0.92,
      tokens: 14208,
      progress: 48,
      retries: 0,
      maxRetries: 2,
      result: null,
      logs: ["Passed anonymous checkout path", "Paused at approval boundary", "Waiting for synthetic reviewer fixture"],
      allowedActions: ["inspect", "export"],
    },
    {
      id: "sable",
      name: "Sable",
      role: "Security reviewer",
      status: "failed",
      runId: "run-1045",
      task: "Scan release artifact for leaked fixtures",
      startedAt: "2026-08-15T14:02:10.000Z",
      updatedAt: "2026-08-15T14:27:01.000Z",
      durationSeconds: 1491,
      costUsd: 1.27,
      tokens: 19003,
      progress: 86,
      retries: 1,
      maxRetries: 2,
      result: "Scanner dependency returned exit code 7.",
      logs: ["Checked 184 artifact paths", "No credential patterns found", "Dependency unavailable: sample-scanner"],
      allowedActions: ["inspect", "retry", "export"],
    },
    {
      id: "quill",
      name: "Quill",
      role: "Documentation writer",
      status: "completed",
      runId: "run-1044",
      task: "Publish operator handoff notes",
      startedAt: "2026-08-15T13:44:20.000Z",
      updatedAt: "2026-08-15T14:12:37.000Z",
      durationSeconds: 1697,
      costUsd: 0.68,
      tokens: 10412,
      progress: 100,
      retries: 0,
      maxRetries: 2,
      result: "Handoff published with 6 verified operator steps.",
      logs: ["Matched terminology to view contract", "Linked six reproducible checks", "Handoff artifact completed"],
      allowedActions: ["inspect", "export"],
    },
  ],
  events: [
    { id: "evt-1", runId: "run-1048", agentId: "atlas", occurredAt: "2026-08-15T14:31:51.000Z", kind: "checkpoint", title: "Atlas reached 72%", detail: "Eight ownership areas mapped; two edges need review." },
    { id: "evt-2", runId: "run-1049", agentId: "lumen", occurredAt: "2026-08-15T14:30:42.000Z", kind: "waiting", title: "Lumen is waiting", detail: "Paused at a documented approval boundary." },
    { id: "evt-3", runId: "run-1045", agentId: "sable", occurredAt: "2026-08-15T14:27:01.000Z", kind: "failed", title: "Sable stopped safely", detail: "A bounded dependency failure left one retry available." },
    { id: "evt-4", runId: "run-1044", agentId: "quill", occurredAt: "2026-08-15T14:12:37.000Z", kind: "completed", title: "Quill delivered the handoff", detail: "Six operator steps are linked to reproducible checks." },
    { id: "evt-5", runId: "run-1048", agentId: "atlas", occurredAt: "2026-08-15T14:18:02.000Z", kind: "started", title: "Atlas started", detail: "Repository analysis began with synthetic source metadata." },
  ],
};
